services:
  eval-etcd:
    image: quay.io/coreos/etcd:v3.5.5
    command: >-
      etcd
      -advertise-client-urls=http://127.0.0.1:2379
      -listen-client-urls=http://0.0.0.0:2379
      --data-dir=/etcd

  eval-minio:
    image: minio/minio:RELEASE.2024-05-28T17-19-04Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: minio server /minio_data

  eval-milvus:
    image: milvusdb/milvus:v2.4.11
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: eval-etcd:2379
      MINIO_ADDRESS: eval-minio:9000
    ports:
      - "127.0.0.1:39530:19530"
      - "127.0.0.1:39591:9091"
    depends_on:
      - eval-etcd
      - eval-minio

