package com.rag.backend.agent.evidence;

/** 对外稳定的低基数决策原因码。 */
public enum EvidenceDecisionReason {
    POLICY_DISABLED,
    DIRECT_SUPPORT_OBSERVED,
    CONFLICT_EXPLANATION_REQUESTED,
    MISSING_QUESTION_SCOPE,
    CONFLICTING_EVIDENCE,
    NO_RETRIEVED_EVIDENCE,
    ALL_EVIDENCE_BELOW_CALIBRATED_THRESHOLD,
    UNTRACEABLE_EVIDENCE,
    EVIDENCE_NOT_RELEVANT,
    INCOMPLETE_DIRECT_SUPPORT
}
