CREATE TABLE documents(id BIGINT PRIMARY KEY, course_id BIGINT, filename VARCHAR(255),
    lifecycle_status VARCHAR(24) DEFAULT 'ACTIVE', active_version_id BIGINT);
CREATE TABLE document_versions(id BIGINT PRIMARY KEY, document_id BIGINT, version_no INT,
    state VARCHAR(32), expected_chunk_count INT, superseded_at TIMESTAMP);
CREATE TABLE knowledge_chunks(id BIGINT PRIMARY KEY, document_id BIGINT, course_id BIGINT,
    document_version_id BIGINT, title VARCHAR(255), content CLOB);
CREATE TABLE chat_sessions(id BIGINT PRIMARY KEY, course_id BIGINT, title VARCHAR(100), updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE chat_messages(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT, role VARCHAR(20), content CLOB, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
